import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/navigation";
import styles from "@/styles";
import Footer from "@/components/footer";

const ibmPlexSans = IBM_Plex_Sans({
  display: "swap",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ibmPlexSans.className}>
        <div className="xl:max-w-[1280px] w-full m-auto mt-6 md:mt-12">
          <Navigation />
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  );
}
